name: CI

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_native_linux:
    name: Build native on linux
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ../libstbi
          make install
      - uses: actions/upload-artifact@master
        with:
          name: linux-x64
          path: runtimes/linux-x64

  build_native_macos:
    name: Build native on macOS
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Build
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 ../libstbi
          make install
      - uses: actions/upload-artifact@master
        with:
          name: osx-x64
          path: runtimes/osx-x64

  build_native_windows:
    name: Build native on Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ../libstbi
          msbuild /v:m /p:Configuration=Release INSTALL.vcxproj

      - uses: actions/upload-artifact@master
        with:
          name: win-x64
          path: runtimes/win-x64

  build_wrapper:
    name: Build C# wrapper
    runs-on: ubuntu-latest
    needs: [build_native_linux, build_native_macos, build_native_windows]

    steps:
      - uses: actions/checkout@v1
      - name: Find latest version
        id: findversion
        uses: oprypin/find-latest-tag@v1.0.5
        with:
          repository: ${{ github.repository }}
          prefix: 'v'
          releases-only: false
      - name: Setup data
        id: datavars
        run: |
          echo "Latest tag is ${{ steps.findversion.outputs.tag }}"
          export SHA_SHORT=$(git rev-parse --short ${{ github.sha }})
          export TAG=$(echo ${{ steps.findversion.outputs.tag }} | awk '{ print substr( $0, 2 ) }')
          echo "::set-output name=version::$TAG-$SHA_SHORT"
      - name: Grab linux binary
        uses: actions/download-artifact@master
        with:
          name: linux-x64
          path: runtimes/linux-x64
      - name: Grab macOS binary
        uses: actions/download-artifact@master
        with:
          name: osx-x64
          path: runtimes/osx-x64
      - name: Grab Windows binary
        uses: actions/download-artifact@master
        with:
          name: win-x64
          path: runtimes/win-x64
      - name: Get version, build, and pack
        run: |
          export GIT_HASH=${{ github.sha }}
          export GIT_BRANCH=${GITHUB_REF#refs/heads/}
          export VERSION=${{ steps.datavars.outputs.version }}
          echo $VERSION $GIT_BRANCH

          sed "s/%COMMIT%/$GIT_HASH/;s/%BRANCH%/$GIT_BRANCH/" < stbi-sharp.csproj > stbi-sharp-build.csproj

          echo Building and packing...
          dotnet pack stbi-sharp-build.csproj -c Release /p:Version=$VERSION
      - uses: actions/upload-artifact@master
        with:
          name: nuget-package
          path: bin/Release/phantombeta.StbiSharp.${{ steps.datavars.outputs.version }}.nupkg